=== apetti1920/CompX_dep/assets/blocks_copy/block.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="block">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:string"/>
                <xs:element name="version">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="major" type="xs:integer"/>
                            <xs:element name="technical" type="xs:integer"/>
                            <xs:element name="editorial" type="xs:integer"/>
                            <xs:element name="letter" type="xs:string" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="thumbnail" type="xs:string"/>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="tags">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tag" minOccurs="1" maxOccurs="unbounded" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="internalData" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="data" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id" type="xs:string"/>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="type" type="xs:string"/>
                                        <xs:element name="value" type="xs:anyType"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="inputPorts" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="port" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id" type="xs:string"/>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="type" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="outputPorts" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="port" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id" type="xs:string"/>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="type" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="pseudoSource" type="xs:string"/>
                <xs:element name="display" minOccurs="0">
                    <xs:complexType>
                        <xs:choice>
                            <xs:sequence>
                                <xs:element name="displayStaticPath" type="xs:string"/>
                                <xs:element name="displayDynamicPath" type="xs:string" minOccurs="0"/>
                            </xs:sequence>
                            <xs:sequence>
                                <xs:element name="displayDynamicPath" type="xs:string"/>
                            </xs:sequence>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="callback" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== apetti1920/CompX_dep/assets/blocks_copy/constant.xml
<?xml version="1.0" encoding="UTF-8"?>
<block xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="block.xsd">
    <id>57d376e8-c4a1-4a91-bee2-c2bf2acf138a</id>
    <version>
        <major>0</major>
        <technical>0</technical>
        <editorial>1</editorial>
    </version>
    <thumbnail>https://picsum.photos/id/1000/75</thumbnail>
    <name>Constant</name>
    <description>A constant value over time</description>
    <tags>
        <tag>Math</tag>
    </tags>
    <internalData>
        <data>
            <id>886458d2-66f6-4146-9c4c-30fc85976202</id>
            <name>Constant Value</name>
            <type>number</type>
            <value>0</value>
        </data>
    </internalData>
    <outputPorts>
        <port>
            <id>0410fd03-484d-4d19-bcd4-8795be220f79</id>
            <name>z</name>
            <type>number</type>
        </port>
    </outputPorts>
    <pseudoSource>false</pseudoSource>
    <display>
        <![CDATA[
            <g>
                <text x="50%" y="50%" dominantBaseline="middle" textAnchor="middle" style={{font: "italic 6px sans-serif"}}>Constant</text>
            </g>
        ]]>
    </display>
    <callback>return [internalData[886458d2-66f6-4146-9c4c-30fc85976202]];</callback>
</block>

=== apetti1920/CompX_dep/assets/blocks_copy/integral.xml
<?xml version="1.0" encoding="UTF-8"?>
<block xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="block.xsd">
    <id>3dc09f18-0c5d-4684-b3a4-3bbd4fbf3b37</id>
    <version>
        <major>0</major>
        <technical>0</technical>
        <editorial>1</editorial>
    </version>
    <thumbnail>https://picsum.photos/id/1002/75</thumbnail>
    <name>Integral</name>
    <description>A discrete time integration</description>
    <tags>
        <tag>Math</tag>
    </tags>
    <internalData>
        <data>
            <id>bae46021-fc04-42c8-9541-57d73427c04a</id>
            <name>ic</name>
            <type>number</type>
            <value>0</value>
        </data>
    </internalData>
    <inputPorts>
        <port>
            <id>38ba6c97-3413-43c2-925d-5d9f5b235c68</id>
            <name>x</name>
            <type>number</type>
        </port>
    </inputPorts>
    <outputPorts>
        <port>
            <id>a2df1900-5f0f-413b-bf1d-7327f3f80382</id>
            <name>z</name>
            <type>number</type>
        </port>
    </outputPorts>
    <pseudoSource>true</pseudoSource>
    <callback>if (t===0.0){return [internalData[bae46021-fc04-42c8-9541-57d73427c04a]]}else{return [prevOutputs[z]+(dt*0.5*(inputPort[x]+(prevInputs[x]!==null?prevInputs[x]:internalData[bae46021-fc04-42c8-9541-57d73427c04a])))]}</callback>
</block>

=== apetti1920/CompX_dep/assets/blocks_copy/sum.xml
<?xml version="1.0" encoding="UTF-8"?>
<block xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="block.xsd">
    <id>126a376d-13fa-4ce2-81d1-cb364204cfea</id>
    <version>
        <major>0</major>
        <technical>0</technical>
        <editorial>1</editorial>
    </version>
    <thumbnail>https://picsum.photos/id/1005/75</thumbnail>
    <name>Sum</name>
    <description>Sum numbers together</description>
    <tags>
        <tag>Math</tag>
    </tags>
    <internalData>
        <data>
            <id>d47693d1-330d-4939-92d0-ac2e8ebbfb40</id>
            <name>signs</name>
            <type>string</type>
            <value>++</value>
        </data>
    </internalData>
    <inputPorts>
        <port>
            <id>2b328235-1563-4e58-a741-5c95171390e2</id>
            <name>a</name>
            <type>number</type>
        </port>
        <port>
            <id>a52384f4-7216-42bc-866e-f7526e2d3d56</id>
            <name>b</name>
            <type>number</type>
        </port>
    </inputPorts>
    <outputPorts>
        <port>
            <id>5503341e-becd-4295-b3d3-b036b4113968</id>
            <name>z</name>
            <type>number</type>
        </port>
    </outputPorts>
    <pseudoSource>false</pseudoSource>
    <callback>return [inputPort[a]+inputPort[b]];</callback>
</block>

=== apetti1920/CompX_dep/assets/blocks_copy/sin.xml
<?xml version="1.0" encoding="UTF-8"?>
<block xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="block.xsd">
    <id>38388158-ba6e-4de9-96ce-c286ff377de9</id>
    <version>
        <major>0</major>
        <technical>0</technical>
        <editorial>1</editorial>
    </version>
    <thumbnail>https://picsum.photos/id/1004/75</thumbnail>
    <name>Sin</name>
    <description>A sine wave changing with time</description>
    <tags>
        <tag>Math</tag>
    </tags>
    <internalData>
        <data>
            <id>bd1a9549-467c-4f75-84a2-745a75a8bfa3</id>
            <name>Angular Frequency</name>
            <type>number</type>
            <value>1</value>
        </data>
        <data>
            <id>db85fd13-b73b-4471-95a1-f341aadf57e9</id>
            <name>Phase</name>
            <type>number</type>
            <value>0</value>
        </data>
    </internalData>
    <outputPorts>
        <port>
            <id>3959212c-d1f2-45dd-b210-c91b46a67445</id>
            <name>z</name>
            <type>number</type>
        </port>
    </outputPorts>
    <pseudoSource>false</pseudoSource>
    <display>
        <![CDATA[
            <g>
                <text x="50%" y="50%" dominantBaseline="middle" textAnchor="middle" style={{font: "italic 6px sans-serif"}}>Sine</text>
            </g>
        ]]>
    </display>
    <callback>return [Math.sin(internalData[bd1a9549-467c-4f75-84a2-745a75a8bfa3]*t+internalData[db85fd13-b73b-4471-95a1-f341aadf57e9])];</callback>
</block>

=== apetti1920/CompX_dep/assets/blocks_copy/gain.xml
<?xml version="1.0" encoding="UTF-8"?>
<block xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="block.xsd">
    <id>42b75e85-805e-4b40-8145-b4f33ef58a30</id>
    <version>
        <major>0</major>
        <technical>0</technical>
        <editorial>1</editorial>
    </version>
    <thumbnail>https://picsum.photos/id/1001/75</thumbnail>
    <name>Gain</name>
    <description>A constant multiplier over time</description>
    <tags>
        <tag>Math</tag>
    </tags>
    <internalData>
        <data>
            <id>cfb547e5-533f-48dd-8cc3-ab53b7bbd8cc</id>
            <name>gain</name>
            <type>number</type>
            <value>1</value>
        </data>
    </internalData>
    <inputPorts>
        <port>
            <id>efe3a5b9-331b-42c8-baae-49e40b8474b9</id>
            <name>x</name>
            <type>number</type>
        </port>
    </inputPorts>
    <outputPorts>
        <port>
            <id>606af56f-49d6-4b6c-8206-4e7f35092539</id>
            <name>z</name>
            <type>number</type>
        </port>
    </outputPorts>
    <pseudoSource>false</pseudoSource>
    <callback>return [internalData[cfb547e5-533f-48dd-8cc3-ab53b7bbd8cc]*inputPort[x]];</callback>
</block>
